name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Print Node.js version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      # Debugging additional GitHub Actions context (optional)
      - name: Debug GitHub context
        run: echo "${{ toJson(github) }}"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Print Node.js version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy
        run: echo "Deployment successful"
